# Generated by Django 4.2.13 on 2024-05-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('syllabus', models.URLField()),
                ('course_work', models.URLField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook.textbook')),
            ],
        ),
    ]
